"use client";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { StyledProgressiveDance } from "./StyledProgressiveDance";
import * as React from "react";
import { AppCacheProvider } from "@mui/material-nextjs/v13-pagesRouter";
import { ConvexReactClient } from "convex/react";
import { ConvexProviderWithAuth0 } from "convex/react-auth0";
import { Auth0Provider } from "@auth0/auth0-react";

const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
if (!convexUrl) throw new Error("Convex URL not found");
const client = new ConvexReactClient(convexUrl);

const domain = process.env.NEXT_PUBLIC_AUTH0_DOMAIN;
const clientId = process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID;
if (!domain) throw new Error("Auth0 Domain not found.");
if (!clientId) throw new Error("Auth0 Client ID not found.");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Auth0Provider
          /*See @https://docs.convex.dev/auth/auth0*/
          domain={domain!}
          clientId={clientId!}
          authorizationParams={{
            redirect_uri:
              typeof window === "undefined"
                ? undefined
                : window.location.origin,
          }}
          useRefreshTokens={true}
          cacheLocation="localstorage"
        >
          {/*See @https://docs.convex.dev/api/modules/react_auth0 */}
          <ConvexProviderWithAuth0 client={client}>
            {/*
             * Responsible for collecting the CSS generated by MUI System on the server.
             * See @https://mui.com/material-ui/integrations/nextjs/
             * @https://github.com/mui/material-ui/issues/26561#issuecomment-855286153.
             */}

            <AppCacheProvider>
              <AppRouterCacheProvider>
                <StyledProgressiveDance>{children}</StyledProgressiveDance>
              </AppRouterCacheProvider>
            </AppCacheProvider>
          </ConvexProviderWithAuth0>
        </Auth0Provider>
      </body>
    </html>
  );
}
